spring.application.name=demo

#DATABASE CONFIG


spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
#JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000
server.port=8027

#UPLOAD_CONFIG
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#RENDER
app.base-url=${APP_BASE_URL}


cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

#AI
GROQ_API_KEY=${GROQ_API_KEY}

#EMAIL
BREVO_API_KEY=${BREVO_API_KEY:}
SUPPORT_EMAIL=${SUPPORT_EMAIL:}

spring.config.import=optional:file:.env[.properties]
