spring.application.name=demo

#DATABASE CONFIG


spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
#JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000
server.port=8027

#UPLOAD_CONFIG
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB




#MAIL


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#AI
GROQ_API_KEY=${GROQ_API_KEY}

spring.config.import=optional:file:.env[.properties]



